'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Number(n||0).toLocaleString(),short=s=>s?s.slice(0,10)+'…'+s.slice(-6):'—',age=t=>t?`${Math.max(0,Math.floor(Date.now()/1000-t))}s ago`:'—';
const link=(path,label)=>`<a href="${path}">${esc(label)}</a>`,badge=s=>`<span class="badge ${esc(s)}">${esc(s)}</span>`,kv=(a,b)=>`<div class="kv"><span>${esc(a)}</span><span class="hash">${b}</span></div>`,panel=(title,body,more='')=>`<section class="panel"><div class="section-head"><h2>${esc(title)}</h2>${more}</div>${body}</section>`;
async function api(path){const r=await fetch(path,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(r.status===404?'Not found':'Explorer is temporarily unavailable');return r.json()}
function table(head,rows){return `<div class="scroll"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}" class="empty">No entries yet.</td></tr>`}</tbody></table></div>`}
function blockTable(items){return table(['Height','Miner','Txs','Preconfs','Seen'],items.map(b=>`<tr><td>${link('/block/'+b.height,'#'+num(b.height))}</td><td>${['miner1','miner2','service','outsider'].includes(b.miner)?link('/miner/'+b.miner,b.miner):esc(b.miner)}</td><td>${num(b.txids.length)}</td><td>${b.preconf_count}</td><td class="muted">${age(b.observed_at)}</td></tr>`))}
function txTable(items){return table(['Transaction','Type','Status','Block','Value'],items.filter(Boolean).map(t=>`<tr><td>${link('/tx/'+t.txid,short(t.txid))}</td><td>${badge(t.kind)}</td><td>${badge(t.status)}</td><td>${t.height!==null?link('/block/'+t.height,'#'+t.height):'—'}</td><td>${t.kind==='payout'?num(t.payout.amount)+' zat':'<span class="shielded" title="Encrypted on-chain">▓▓▓▓▓▓</span>'}</td></tr>`))}
function pager(page,more){return `<div class="pager">${page?link(location.pathname+'?page='+(page-1),'← Newer'):''}<span class="muted">Page ${page+1}</span>${more?link(location.pathname+'?page='+(page+1),'Older →'):''}</div>`}
let busy=false,summary;
async function render(){if(busy)return;busy=true;try{
 summary=await api('/api/summary');
 const stale=summary.error||summary.stalled||Date.now()/1000-summary.indexed_at>30;
 $('connection').hidden=!stale;$('connection').className=stale?'warn':'';$('connection').textContent=summary.error||(stale?'Chain updates delayed.':'');
 $('updated').textContent=`Indexed ${age(summary.indexed_at)} · Chain ${short(summary.chain_id)}`;
 $('stats').innerHTML=[['Preconfirmed payments',num(summary.included),`${num(summary.pending)} pending · ${num(summary.failed)} failed`],['Miner revenue paid',num(summary.paid)+' zat','']].map(s=>`<div class="stat"><span class="label">${s[0]}</span><strong>${s[1]}</strong>${s[2]?`<small>${s[2]}</small>`:''}</div>`).join('');
 const path=location.pathname,page=Number(new URLSearchParams(location.search).get('page')||0);let html='';
 document.body.classList.toggle('detail',path!=='/');
 document.querySelectorAll('.links a').forEach(a=>a.classList.toggle('active',a.pathname===path));
 if(path==='/protocol'){document.title='Protocol | PreconfScan';return;}
 if(path==='/'){
  const [bs,ts,ps]=await Promise.all([api('/api/blocks'),api('/api/txs'),api('/api/txs?filter=pending')]);
  html=`<div class="grid">${panel('Latest blocks',blockTable(bs.items.slice(0,8)),link('/blocks','see all →'))}${panel('Latest transactions',txTable(ts.items.slice(0,8)),link('/txs','see all →'))}</div>`+panel('Awaiting inclusion',txTable(ps.items.slice(0,6)),link('/pending','pending set →'));
 }else if(path==='/blocks'){const d=await api('/api/blocks?page='+page);html=panel('Blocks',blockTable(d.items))+pager(page,d.has_more);
 }else if(path==='/txs'||path==='/pending'){const d=await api('/api/txs?page='+page+(path==='/pending'?'&filter=pending':''));html=panel(path==='/pending'?'Pending preconfirmations':'Transactions',txTable(d.items))+pager(page,d.has_more);
 }else if(path.startsWith('/block/')){
  const b=await api('/api'+path);const txs=await Promise.all(b.txids.map(id=>api('/api/tx/'+id)));
  html=`<p class="crumb">${link('/blocks','Blocks')} / ${b.height}</p><h2 class="title">BLOCK #${num(b.height)}</h2>`+panel('Block details',`<div class="details">${kv('Hash',esc(b.hash))}${kv('Miner',link('/miner/'+b.miner,b.miner))}${kv('Confirmations',num(b.confirmations))}${kv('Header time (regtest)',esc(new Date(b.time*1000).toISOString()))}${kv('Size',b.size===null?'—':num(b.size)+' bytes')}${kv('Preconfirmed payments',num(b.preconf_count)+' / '+num(b.txids.length)+' total transactions')}${kv('Collected service fees',num(b.service_fees)+' zat')}${kv('Miner revenue share',b.payouts.map(p=>`${num(p.amount)} zat · ${badge(p.status)} ${p.txid?link('/tx/'+p.txid,short(p.txid)):'awaiting two confirmations'}`).join('<br>')||'No assigned payout')}${kv('Previous block',b.height>0?link('/block/'+(b.height-1),'#'+(b.height-1)):'Genesis')}</div>`)+panel('Transactions',txTable(txs));
 }else if(path.startsWith('/tx/')){
  const t=await api('/api'+path),r=t.preconf,p=t.payout;
  html=`<p class="crumb">${link('/txs','Transactions')} / ${short(t.txid)}</p><h2 class="title">${t.kind.toUpperCase()} TRANSACTION</h2>`+panel('Transaction details',`<div class="details">${kv('Transaction ID',esc(t.txid))}${kv('Status',badge(t.status))}${kv('Block',t.height!==null?link('/block/'+t.height,'#'+t.height):'Not included')}${kv('Confirmations',num(t.confirmations))}${kv('Value',t.kind==='payout'?num(p.amount)+' zat · disclosed by demo service':'<span class="shielded">▓▓▓▓▓▓</span> · shielded')}${r?kv('Service fee',num(r.fee)+' zat'+(r.status==='included'?' collected':' proposed')):''}${r?.failure_reason?kv('Failure reason',esc(r.failure_reason)):''}</div>`);
  if(r)html+=panel('Preconfirmation receipt',`<div class="details">${kv('Acceptance','Signed and persisted by the singleton service')}${kv('Payload',`<pre>${esc(atob(r.receipt.payload))}</pre>`)}${kv('Signature',`<pre>${esc(r.receipt.signature)}</pre>`)}</div><p class="note">A receipt records acceptance, not a consensus guarantee. Participating miners prioritize this transaction over conflicting mempool transactions.</p>`);
  if(p)html+=panel('Miner payout',`<div class="details">${kv('State',badge(p.status))}${kv('Earned in block',link('/block/'+p.block.height,'#'+p.block.height))}${kv('Miner share',num(p.amount)+' zat · 98% of collected service fees')}${kv('Payout transaction',p.txid?link('/tx/'+p.txid,p.txid):'Not signed yet')}${kv('Accepted payments',p.txids.map(id=>link('/tx/'+id,short(id))).join(' · '))}${p.reason?kv('Reason',esc(p.reason)):''}</div>`);
 }else if(path==='/miners'||path.startsWith('/miner/')){
  const d=await api('/api/miners');let miners=d.items;if(path.startsWith('/miner/'))miners=miners.filter(m=>m.name===path.split('/')[2]);
  html='<h2 class="title">MINERS</h2><div class="split">'+miners.map(m=>panel(m.name,`<div class="miner"><span class="count">${num(m.blocks)}</span> blocks<p>${num(m.payments)} preconfirmed payments included</p><p>${num(m.earned)} zat earned · ${num(m.paid)} zat paid</p><p>Recent blocks<br>${m.recent_blocks.map(h=>link('/block/'+h,'#'+h)).join(' · ')||'No blocks yet'}</p></div>`,link('/miner/'+m.name,'details →'))).join('')+'</div>';
 }else if(path==='/activity'){
  const d=await api('/api/activity');html=panel('Demo activity',table(['Time','Event','Details'],d.items.map(e=>`<tr><td class="muted">${new Date(e.time*1000).toLocaleTimeString()}</td><td>${esc(e.event.replaceAll('_',' '))}</td><td>${e.txid?link('/tx/'+e.txid,short(e.txid)):e.height?link('/block/'+e.height,'#'+e.height):esc(e.phase||'')}${e.count!==undefined?' · '+e.count+' payments':''}${e.miner?' · '+esc(e.miner):''}</td></tr>`)))+'<p class="note">“Double spend rejected” means the service rejected a second spend. This live workload uses participating miners; it does not force outsider wins.</p>';
 }
 $('page').innerHTML=html;document.title=(path==='/'?'Live explorer':path.slice(1).replaceAll('/',' · '))+' | PreconfScan';
 }catch(e){$('connection').hidden=false;$('connection').className='warn';$('connection').textContent=e.message;if(location.pathname!=='/protocol')$('page').innerHTML=panel('Unavailable',`<p class="empty">${esc(e.message)}. ${link('/','Return home →')}</p>`);}finally{busy=false}}
$('search').onsubmit=async e=>{e.preventDefault();const q=$('query').value.trim().toLowerCase();$('search-error').textContent='';if(/^\d{1,10}$/.test(q)){location.href='/block/'+q;return}if(!/^[a-f0-9]{64}$/.test(q)){$('search-error').textContent='Enter a block height or a 64-character transaction/block hash.';return}try{await api('/api/tx/'+q);location.href='/tx/'+q}catch{try{await api('/api/block/'+q);location.href='/block/'+q}catch{$('search-error').textContent='No matching transaction or block in this devnet.'}}};
render();setInterval(render,3000);
